#!/bin/bash

# Railway Deployment Setup Script
# This script helps you set the correct environment variables on Railway

echo "==================================="
echo "Railway HTTPS Fix - Setup Script"
echo "==================================="
echo ""
echo "This script will guide you through fixing the 'Form is not secure' issue."
echo ""

# Get Railway project URL
echo "Step 1: Get your Railway URL"
echo "----------------------------"
echo "What is your Railway app URL?"
echo "Example: nish-leave-mgt-system-production.up.railway.app"
echo ""
read -p "Enter your Railway domain (without https://): " RAILWAY_DOMAIN

APP_URL="https://${RAILWAY_DOMAIN}"

echo ""
echo "Step 2: Environment Variables to Set on Railway"
echo "------------------------------------------------"
echo ""
echo "Go to your Railway dashboard and set these variables:"
echo ""
echo "APP_ENV=production"
echo "APP_DEBUG=false"
echo "APP_URL=${APP_URL}"
echo ""
echo "SESSION_DRIVER=database"
echo "SESSION_SECURE_COOKIE=true"
echo "SESSION_HTTP_ONLY=true"
echo "SESSION_SAME_SITE=lax"
echo ""
echo "Step 3: Run These Commands After Deployment"
echo "--------------------------------------------"
echo ""
echo "In Railway's terminal or during build, run:"
echo ""
echo "php artisan migrate --force"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo ""
echo "Step 4: Verify"
echo "--------------"
echo ""
echo "After deployment:"
echo "1. Visit: ${APP_URL}/login"
echo "2. Check browser console (F12) - should see no warnings"
echo "3. Try logging in - should work on first attempt"
echo "4. No 'Form is not secure' warning should appear"
echo ""
echo "==================================="
echo "Setup complete! Deploy and test."
echo "==================================="
